"""Implementation for the ``atelier snapshot`` command."""

from __future__ import annotations

import datetime as dt
from pathlib import Path

from .. import config, git, paths, sessions, workspace
from ..io import die, say, warn
from .resolve import resolve_current_project, resolve_workspace_target


def _format_count(value: int | None) -> str:
    return str(value) if value is not None else "unknown"


def _read_text(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return None


def _append_file_section(lines: list[str], title: str, text: str | None) -> None:
    lines.extend(["", f"## {title}", ""])
    if text is None:
        lines.append("_Missing_")
        return
    content = text.rstrip()
    lines.extend(["```text", content, "```"] if content else ["```text", "```"])


def _append_session_section(
    lines: list[str],
    workspace_config: config.WorkspaceConfig | None,
    enlistment_path: str,
    workspace_branch: str,
) -> None:
    session_lines: list[str] = []
    if workspace_config is not None:
        stored_session = workspace_config.workspace.session
        if stored_session is not None:
            if stored_session.agent:
                session_lines.append(f"- Stored agent: `{stored_session.agent}`")
            if stored_session.id:
                session_lines.append(f"- Stored session id: `{stored_session.id}`")
            if stored_session.resume_command:
                session_lines.append(
                    f"- Stored resume command: `{stored_session.resume_command}`"
                )

    workspace_uid = None
    if workspace_config is not None:
        workspace_uid = workspace_config.workspace.uid
    discovered = sessions.find_codex_session(
        enlistment_path, workspace_branch, workspace_uid
    )
    if discovered:
        session_lines.append(f"- Discoverable Codex session id: `{discovered}`")

    if not session_lines:
        return

    lines.extend(
        [
            "",
            "## Agent Session (Best-effort)",
            "",
            "This section is best-effort and may be incomplete.",
            "",
            *session_lines,
        ]
    )


def _build_snapshot(
    *,
    workspace_dir: Path,
    repo_dir: Path | None,
    workspace_branch: str,
    mainline_branch: str | None,
    enlistment_path: str,
    workspace_config: config.WorkspaceConfig | None,
    git_path: str | None,
) -> str:
    today = dt.datetime.now(tz=dt.timezone.utc).strftime("%Y-%m-%d")
    lines: list[str] = [
        "# Workspace Snapshot",
        "",
        "Generated by `atelier snapshot`.",
        "",
        f"- Date: {today}",
        f"- Workspace: `{workspace_branch}`",
        f"- Workspace dir: `{workspace_dir}`",
    ]

    success_text = _read_text(workspace_dir / "SUCCESS.md")
    persist_text = _read_text(workspace_dir / "PERSIST.md")
    background_text = _read_text(workspace_dir / "BACKGROUND.md")

    _append_file_section(lines, "SUCCESS.md", success_text)
    _append_file_section(lines, "PERSIST.md", persist_text)
    if background_text is not None:
        _append_file_section(lines, "BACKGROUND.md", background_text)

    if repo_dir is None:
        lines.extend(
            [
                "",
                "## Repo Status",
                "",
                "_Workspace repo unavailable; git snapshot data omitted._",
            ]
        )
        _append_session_section(
            lines,
            workspace_config,
            enlistment_path,
            workspace_branch,
        )
        return "\n".join(lines).rstrip() + "\n"

    current_branch = git.git_current_branch(repo_dir, git_path=git_path)
    clean = git.git_is_clean(repo_dir, git_path=git_path)
    status_lines = git.git_status_porcelain(repo_dir, git_path=git_path)

    lines.extend(
        [
            "",
            "## Git Status",
            "",
            f"- Repo: `{repo_dir}`",
            f"- Branch: `{current_branch or 'unknown'}`",
            f"- Clean: {workspace.format_status(clean)}",
        ]
    )
    if status_lines:
        lines.extend(["", "```text", *status_lines, "```"])
    else:
        lines.append("- Status: clean")

    if not mainline_branch:
        mainline_branch = "unknown"

    ahead = git.git_commits_ahead(
        repo_dir, mainline_branch, workspace_branch, git_path=git_path
    )
    behind = git.git_commits_ahead(
        repo_dir, workspace_branch, mainline_branch, git_path=git_path
    )
    diff_names = git.git_diff_name_status(
        repo_dir, mainline_branch, workspace_branch, git_path=git_path
    )
    diff_stat = git.git_diff_stat(
        repo_dir, mainline_branch, workspace_branch, git_path=git_path
    )

    lines.extend(
        [
            "",
            "## Mainline Comparison",
            "",
            f"- Mainline: `{mainline_branch}`",
            f"- Commits ahead: {_format_count(ahead)}",
            f"- Commits behind: {_format_count(behind)}",
        ]
    )
    if diff_names:
        lines.extend(
            ["", "### Files Changed", "", *[f"- `{line}`" for line in diff_names]]
        )
    else:
        lines.append("- Files changed: none")
    if diff_stat:
        lines.extend(["", "### Diffstat", "", "```text", *diff_stat, "```"])

    tracked_files = git.git_ls_files(repo_dir, git_path=git_path)
    lines.extend(["", "## File List (tracked)", ""])
    if tracked_files:
        lines.extend(["```text", *tracked_files, "```"])
    else:
        lines.append("_None_")

    _append_session_section(
        lines,
        workspace_config,
        enlistment_path,
        workspace_branch,
    )

    return "\n".join(lines).rstrip() + "\n"


def snapshot_workspace(args: object) -> None:
    """Write a workspace snapshot summary."""
    workspace_name = getattr(args, "workspace_name", None)
    if not workspace_name:
        die("workspace branch must not be empty")

    project_root, project_config, enlistment_path = resolve_current_project()
    git_path = config.resolve_git_path(project_config)
    branch, workspace_dir = resolve_workspace_target(
        project_root=project_root,
        project_config=project_config,
        enlistment_path=enlistment_path,
        workspace_name=str(workspace_name),
        raw=False,
        git_path=git_path,
    )

    repo_dir = workspace_dir / "repo"
    resolved_repo: Path | None = None
    if repo_dir.exists() and git.git_is_repo(repo_dir, git_path=git_path):
        resolved_repo = repo_dir
    elif repo_dir.exists():
        warn("workspace repo exists but is not a git repository")
    else:
        warn("workspace repo missing; snapshot will omit git data")

    workspace_config = config.load_workspace_config(
        paths.workspace_config_path(workspace_dir)
    )

    mainline_branch = None
    if resolved_repo is not None:
        mainline_branch = git.git_default_branch(resolved_repo, git_path=git_path)

    snapshot_path = workspace_dir / "SNAPSHOT.md"
    content = _build_snapshot(
        workspace_dir=workspace_dir,
        repo_dir=resolved_repo,
        workspace_branch=branch,
        mainline_branch=mainline_branch,
        enlistment_path=enlistment_path,
        workspace_config=workspace_config,
        git_path=git_path,
    )
    snapshot_path.write_text(content, encoding="utf-8")
    say(f"Wrote snapshot to {snapshot_path}")
