"""Public contract for the reusable Beads library surface."""

from .client import AsyncBeadsClient, Beads, BeadsTransport
from .compatibility import (
    DEFAULT_COMPATIBILITY_POLICY,
    DEFAULT_MINIMUM_BD_VERSION,
    CapabilityRule,
    CompatibilityPolicy,
    OperationContract,
)
from .errors import (
    BeadError,
    BeadsCommandError,
    BeadsCompatibilityError,
    BeadsParseError,
    BeadsTimeoutError,
    CapabilityMismatchError,
    UnsupportedOperationError,
    UnsupportedVersionError,
)
from .models import (
    BeadsCapability,
    BeadsCommandHelp,
    BeadsCommandRequest,
    BeadsCommandResult,
    BeadsEnvironment,
    BeadsStartupState,
    CloseIssueRequest,
    CreateIssueRequest,
    DependencyMutationRequest,
    IssueRecord,
    IssueReference,
    ListIssuesRequest,
    OperationOutputMode,
    ReadyIssuesRequest,
    SemanticVersion,
    ShowIssueRequest,
    SupportedOperation,
    UpdateIssueRequest,
)
from .overflow import (
    AsyncEventHistoryOverflowRecovery,
    EventHistoryOverflowRepairResult,
    SyncEventHistoryOverflowRecovery,
    maybe_repair_after_event_history_overflow,
    maybe_repair_after_event_history_overflow_sync,
    overflow_repair_result_proves_convergence,
)
from .process import (
    SubprocessBeadsClient,
    SubprocessBeadsTransport,
    decode_help_output,
    decode_version_output,
)
from .sync import SyncBeadsClient, SyncBeadsProtocol, build_sync_beads_client
from .testing import RecordingBeadsTransport, ScriptedBeadsTransport

__all__ = [
    "DEFAULT_COMPATIBILITY_POLICY",
    "DEFAULT_MINIMUM_BD_VERSION",
    "AsyncBeadsClient",
    "AsyncEventHistoryOverflowRecovery",
    "BeadError",
    "Beads",
    "BeadsCapability",
    "BeadsCommandError",
    "BeadsCommandHelp",
    "BeadsCommandRequest",
    "BeadsCommandResult",
    "BeadsCompatibilityError",
    "BeadsEnvironment",
    "BeadsParseError",
    "BeadsStartupState",
    "BeadsTimeoutError",
    "BeadsTransport",
    "CapabilityMismatchError",
    "CapabilityRule",
    "CloseIssueRequest",
    "CompatibilityPolicy",
    "CreateIssueRequest",
    "DependencyMutationRequest",
    "EventHistoryOverflowRepairResult",
    "IssueRecord",
    "IssueReference",
    "ListIssuesRequest",
    "OperationContract",
    "OperationOutputMode",
    "ReadyIssuesRequest",
    "RecordingBeadsTransport",
    "ScriptedBeadsTransport",
    "SemanticVersion",
    "ShowIssueRequest",
    "SubprocessBeadsClient",
    "SubprocessBeadsTransport",
    "SupportedOperation",
    "SyncBeadsClient",
    "SyncBeadsProtocol",
    "SyncEventHistoryOverflowRecovery",
    "UnsupportedOperationError",
    "UnsupportedVersionError",
    "UpdateIssueRequest",
    "build_sync_beads_client",
    "decode_help_output",
    "decode_version_output",
    "maybe_repair_after_event_history_overflow",
    "maybe_repair_after_event_history_overflow_sync",
    "overflow_repair_result_proves_convergence",
]
