# Template for Atelier projects.
# Replace placeholders like __PROJECT_NAME__ before use.

project:
  name: __PROJECT_NAME__
  repo:
    url: __REPO_URL__
    default_branch: __DEFAULT_BRANCH__

workspace:
  branch_prefix: __BRANCH_PREFIX__
  naming_pattern: "{type}-{slug}"

defaults:
  pr_base: __DEFAULT_BRANCH__
  delete_branch_on_merge: true
  delete_workspace_on_merge: true
