"""Public contract for the typed Beads client package."""

from .client import AsyncBeadsClient, BeadsTransport
from .compatibility import (
    DEFAULT_COMPATIBILITY_POLICY,
    DEFAULT_MINIMUM_BD_VERSION,
    CapabilityRule,
    CompatibilityPolicy,
    OperationContract,
)
from .errors import (
    BeadError,
    BeadsCommandError,
    BeadsCompatibilityError,
    BeadsParseError,
    BeadsTimeoutError,
    CapabilityMismatchError,
    UnsupportedOperationError,
    UnsupportedVersionError,
)
from .models import (
    BeadsCapability,
    BeadsCommandRequest,
    BeadsCommandResult,
    BeadsEnvironment,
    CloseIssueRequest,
    CreateIssueRequest,
    DependencyMutationRequest,
    IssueRecord,
    IssueReference,
    ListIssuesRequest,
    OperationOutputMode,
    ReadyIssuesRequest,
    SemanticVersion,
    ShowIssueRequest,
    SupportedOperation,
    UpdateIssueRequest,
)

__all__ = [
    "DEFAULT_COMPATIBILITY_POLICY",
    "DEFAULT_MINIMUM_BD_VERSION",
    "AsyncBeadsClient",
    "BeadError",
    "BeadsCapability",
    "BeadsCommandError",
    "BeadsCommandRequest",
    "BeadsCommandResult",
    "BeadsCompatibilityError",
    "BeadsEnvironment",
    "BeadsParseError",
    "BeadsTimeoutError",
    "BeadsTransport",
    "CapabilityMismatchError",
    "CapabilityRule",
    "CloseIssueRequest",
    "CompatibilityPolicy",
    "CreateIssueRequest",
    "DependencyMutationRequest",
    "IssueRecord",
    "IssueReference",
    "ListIssuesRequest",
    "OperationContract",
    "OperationOutputMode",
    "ReadyIssuesRequest",
    "SemanticVersion",
    "ShowIssueRequest",
    "SupportedOperation",
    "UnsupportedOperationError",
    "UnsupportedVersionError",
    "UpdateIssueRequest",
]
